### ISSUE TITLE
Don't limit the RDNSS lifetime to the default router lifetime?

### ISSUE THREAD

**Issue by NeoRaider** [sbyx/odhcp6c#21]
We recently hit the problem that it is not possible to specify a RDNSS record in a router advertisement when AdvDefaultLifetime is 0, as the RDNSS lifetime is bounded by the default router lifetime.

I'm aware that RFC6106 explicitly mandates this behaviour, but I don't think it makes any sense (why would a RA even contain a RDNSS record with a higher lifetime that its AdvDefaultLifetime if it's always shortened anyways?), and it makes it impossible to announce a DNS server without also announcing a default route (even when the DNS server address might be in one of the prefixes that is announced by the same RA and thus reachable without a default route).

I've been looking for other discussions about this topic; so far I've found the (unfortunately expired) RFC draft http://ietfreport.isoc.org/idref/draft-gont-6man-slaac-dns-config-issues/ which mentions the same issue in Appendix A, coming to the same conclusion that the default router lifetime shouldn't affect the RDNSS lifetime.

**Comment by sbyx** [comment]
i recognize your issue, however the draft is expired and i'm keeping the old behavior for now.

if you could make this into a command-line option i would be fine to accept this as opt-in behavior based on a switch.
