### ISSUE TITLE
not seeing a /60 on comcast

### ISSUE THREAD

**Issue by dtaht** [sbyx/odhcp6c#34]
I started this bug on the wrong daemon (see: https://github.com/sbyx/odhcpd/issues/42 )

I am building from trunk and requesting a /60 via either ip6assign or reqprefix... Not getting one. I used to get one. I will check to see if I get one from an older box on the same link.

Have a horde of other dhcp issues... 

And the answer seems to be two servers are providing prefixes, but the preference 255 one is only a /64. This is me only apparently getting a /64

http://snapon.lab.bufferbloat.net/~d/comcast_dhcp_issues.cap

**Comment by sbyx** [comment]
Actually looking at the advertising handling, this behavior has been there for a long time:

https://github.com/sbyx/odhcp6c/blame/master/src/dhcpv6.c#L873
https://github.com/sbyx/odhcp6c/commit/0c764d13ba834d6be53c4312007584613dec3a1e

The handling basically hasn't changed since late 2013, so I wonder why it supposedly works with a slightly earlier version. What was the package version of the odhcp6c that worked?

**Comment by dtaht** [comment]
I will plug in the other box I was using... bb in 10

**Comment by dtaht** [comment]
return (rc > 1 || (pref == 255 && cand.preference > 0)) ? 1 : -1; // cand.preference >= 0

**Comment by dtaht** [comment]
ok, I booted up the other box. 1) it did not require a reboot of the cablemodem to get ipv4, it got a native ipv4 address, AND an ipv6 /60 delegation.

 BARRIER BREAKER (3.10.50-1, r41861)

**Comment by sbyx** [comment]
I went through the changes between the BB version and the latest:
https://github.com/sbyx/odhcp6c/compare/67b311ab81736b35858664219d345844ab08fcc7...master

there were no changes to the server election logic and no commits that (to me) seem to effect it in any way either.

**Comment by sbyx** [comment]
could this be due to the server remembering state (i.e. DUID) of your old router and thus behaving differently with the new one, not because of the client version but because of the changed identity?

**Comment by dtaht** [comment]
We had that basic behavior with the other bug series we went through, with the non-standard error message (was that ever resolved?) - yes.

I guess I could try re-using the same duid (option to configure?) - but on the other hand, I can see that this use case needs to be handled generally. Maybe getting a /60 is gated on lease expiry for the other box?

Hmm. I could try plugging both boxes into the modem at the same time to watch what happens...

**Comment by dtaht** [comment]
Anyway... after waiting 20 minutes of doing futile dhcp requests, and then doing a reboot of the modem, I got a real ipv4 address and eventually an ipv6 /60 from the new chaos calmer box. Which of course ended up different from the one distributed earlier, which is not retracted... and another reboot of the router led to no replies again, either. 

Question - is the acquisition of the ipv6 prefix and addr blocked by udhcp having to finish first, or can odhcp6c run in parallel?



root@cake:~# ip -6 route
default from :: via fe80::201:5cff:fe63:e446 dev eth0  proto static  metric 512 
default from 2001:558:6045:bd:454b:b3bf:c4f:fc9b via fe80::201:5cff:fe63:e446 dev eth0  proto static  metric 512 
default from 2601:9:3603:27b0::/60 via fe80::201:5cff:fe63:e446 dev eth0  proto static  metric 512 
2601:9:3601:cb80::/60 from :: via fe80::120d:7fff:fe64:c990 dev wlan1  proto babel  metric 1024 
2601:9:3601:cb80::/60 from 2601:9:3600:ba4::/64 via fe80::120d:7fff:fe64:c990 dev wlan1  proto babel  metric 1024 
2601:9:3601:cb80::/60 from 2601:9:3601:cb82::/64 via fe80::120d:7fff:fe64:c990 dev wlan1  proto babel  metric 1024 
2601:9:3603:27b0::/64 dev eth1  proto static  metric 1024 
2601:9:3603:27b1::/64 dev wlan0  proto static  metric 1024 
unreachable 2601:9:3603:27b0::/60 dev lo  proto static  metric 2147483647  error -128
fde5:dfb9:df90:fff3::1 via fe80::260a:64ff:fecc:247d dev wlan1  proto babel  metric 1024 
fe80::/64 dev eth1  proto kernel  metric 256 
fe80::/64 dev eth0  proto kernel  metric 256 
fe80::/64 dev wlan1  proto kernel  metric 256 
fe80::/64 dev wlan0  proto kernel  metric 256 
fe80::/64 dev ifb4eth0  proto kernel  metric 256

**Comment by sbyx** [comment]
That depends on your configuration.
In trunk and the upcoming CC the configuration looks like this:


```
config interface wan
    option ifname eth0
    option proto dhcp

config interface wan6
    option ifname eth1
    option proto dhcpv6
```

this allows parallel bringup. If you use the old "option ifname @wan" notation for the dhcpv6 interface then ipv6 is only started after IPv4 is successfully brought up.

**Comment by sbyx** [comment]
Also I guess I'll close the issue since it seems to be resolved.

**Comment by dtaht** [comment]
I was not using the @wan syntax, but it certainly seemed serialized. The issue is still open to me, but does seem like the handoff needs to go back into comcast's bug db overall as to handling preference 255 (or why that happens)

**Comment by sbyx** [comment]
If you don't use the @-syntax in ifname and use a physical device (e.g. ethX in both dhcp and dhcpv6 section) instead it should in fact be parallelized. If it isn't I should probably have a look. You could easily check this by seeing if the odchp6c process is running while the dhcpv4 isn't complete yet.

**Comment by dtaht** [comment]
both daemons are running. In my captures the dhcpv4 was always first to win - but this is probably closely related to me having to reboot the cable modem every time - BUT - I would have hoped that the ipv6 negotiation would succeed even while the ipv4 one was failing (some connectivity better than none). So I would suspect, also, that ipv6 was gated on ipv4 on their side.
